#Requires -Version 5.1
<#
.SYNOPSIS
    Generate integration_config.yml from Windows Credential Manager.
    Run this yourself — never delegate to an AI assistant.

.USAGE
    .\make_integration_config.ps1 [-HostMac "de:ad:be:ef:00:01"]
#>
param(
    [string]$HostMac = "aa:bb:cc:dd:ee:ff"
)

$ErrorActionPreference = "Stop"

$code = @'
using System;
using System.Runtime.InteropServices;
using System.Text;
public class WinCred {
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CREDENTIAL {
        public int Flags; public int Type; public string TargetName;
        public string Comment;
        public System.Runtime.InteropServices.ComTypes.FILETIME LastWritten;
        public int CredentialBlobSize; public IntPtr CredentialBlob;
        public int Persist; public int AttributeCount; public IntPtr Attributes;
        public string TargetAlias; public string UserName;
    }
    [DllImport("advapi32.dll", EntryPoint="CredReadW", CharSet=CharSet.Unicode, SetLastError=true)]
    public static extern bool CredRead(string target, int type, int flags, out IntPtr cred);
    [DllImport("advapi32.dll", SetLastError=true)]
    public static extern void CredFree(IntPtr cred);
    public static string[] Get(string target) {
        IntPtr ptr;
        if (!CredRead(target, 1, 0, out ptr)) return null;
        var c = (CREDENTIAL)Marshal.PtrToStructure(ptr, typeof(CREDENTIAL));
        byte[] blob = new byte[c.CredentialBlobSize];
        Marshal.Copy(c.CredentialBlob, blob, 0, blob.Length);
        string pwd = Encoding.Unicode.GetString(blob);
        CredFree(ptr);
        return new string[] { c.UserName, pwd };
    }
}
'@
Add-Type -TypeDefinition $code

$cred = [WinCred]::Get("community-freebox-ansible")
if (-not $cred) {
    Write-Error "Credential 'community-freebox-ansible' not found in Windows Credential Manager."
    exit 1
}

$out = Join-Path $PSScriptRoot "integration_config.yml"
@"
---
# Generated by make_integration_config.ps1 — DO NOT COMMIT (gitignored)
freebox_url: http://mafreebox.freebox.fr
freebox_app_id: $($cred[0])
freebox_app_token: $($cred[1])

# MAC of a known LAN host for the freebox_lan_host target
freebox_test_host_mac: "$HostMac"
"@ | Set-Content -Path $out -Encoding utf8

Write-Host "OK: $out written (app_id=$($cred[0]), token=$($cred[1].Length) chars)" -ForegroundColor Green
