#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Pair with the Freebox and write integration_config.yml.

Usage:
    python3 tests/integration/pair_freebox.py

The app_token is NEVER printed to stdout. It flows:
    Freebox HTTP → Python memory → integration_config.yml (chmod 600, gitignored)

Run once; re-run to replace an expired/revoked token.
"""

from __future__ import print_function

import json
import os
import sys
import time

try:
    from urllib.request import urlopen, Request
    from urllib.error import URLError
except ImportError:
    from urllib2 import urlopen, Request, URLError  # type: ignore[no-redef]

FREEBOX_URL = "http://mafreebox.freebox.fr/api/v6"
APP_ID = "mipsou.freebox"
APP_NAME = "community.freebox ansible"
APP_VERSION = "0.2.0"
DEVICE_NAME = "ansible"

POLL_INTERVAL = 3
POLL_MAX = 100  # ~5 min

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_CONFIG_FILE = os.path.join(_SCRIPT_DIR, "integration_config.yml")


def _http_post(path, body):
    data = json.dumps(body).encode("utf-8")
    req = Request(
        FREEBOX_URL + path,
        data=data,
        headers={"Content-Type": "application/json"},
    )
    with urlopen(req, timeout=10) as resp:
        return json.loads(resp.read().decode("utf-8"))


def _http_get(path):
    with urlopen(FREEBOX_URL + path, timeout=10) as resp:
        return json.loads(resp.read().decode("utf-8"))


def _write_config(app_id, app_token):
    """Write integration_config.yml with chmod 600. Token never printed."""
    host_mac = os.environ.get("FREEBOX_TEST_HOST_MAC", "aa:bb:cc:dd:ee:ff")
    content = (
        "---\n"
        "# Generated by pair_freebox.py — gitignored, never commit\n"
        "freebox_url: http://mafreebox.freebox.fr\n"
        "freebox_app_id: {app_id}\n"
        "freebox_app_token: {app_token}\n"
        "\n"
        "# MAC of a known LAN host for freebox_lan_host target\n"
        "freebox_test_host_mac: \"{host_mac}\"\n"
    ).format(app_id=app_id, app_token=app_token, host_mac=host_mac)

    # Write atomically: temp file → rename.
    tmp = _CONFIG_FILE + ".tmp"
    old_umask = os.umask(0o177)  # rw------- for new files
    try:
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(content)
    finally:
        os.umask(old_umask)
    os.replace(tmp, _CONFIG_FILE)
    os.chmod(_CONFIG_FILE, 0o600)
    print("✓ integration_config.yml written (chmod 600).")


def main():
    # 1. Request pairing
    print("Requesting Freebox pairing (app_id=%s)..." % APP_ID)
    try:
        resp = _http_post(
            "/login/authorize/",
            {
                "app_id": APP_ID,
                "app_name": APP_NAME,
                "app_version": APP_VERSION,
                "device_name": DEVICE_NAME,
            },
        )
    except URLError as exc:
        sys.exit("HTTP error: %s\nIs the Freebox reachable at %s?" % (exc, FREEBOX_URL))

    if not resp.get("success"):
        sys.exit("Pairing request failed: %s" % resp)

    result = resp["result"]
    app_token = result["app_token"]
    track_id = result["track_id"]

    print("→ Approve on your Freebox screen (track_id=%d)." % track_id)
    print("  Grant ALL permissions (including Contrôle parental / parental).")
    print("  Polling every %ds (max %ds)..." % (POLL_INTERVAL, POLL_INTERVAL * POLL_MAX))

    # 2. Poll for approval
    for attempt in range(POLL_MAX):
        time.sleep(POLL_INTERVAL)
        try:
            status_resp = _http_get("/login/authorize/%d" % track_id)
        except URLError:
            continue
        status = status_resp.get("result", {}).get("status", "unknown")
        if status == "granted":
            print("\n✓ Approved by Freebox!")
            break
        elif status in ("denied", "timeout"):
            sys.exit("\nPairing %s — aborting." % status)
        else:
            sys.stdout.write(
                "  [%3ds] status=%s   \r" % ((attempt + 1) * POLL_INTERVAL, status)
            )
            sys.stdout.flush()
    else:
        sys.exit("\nTimeout: approval not received within %ds." % (POLL_INTERVAL * POLL_MAX))

    # 3. Write config — token never printed, only written to chmod 600 file
    _write_config(APP_ID, app_token)
    print("Done. Run: bash tests/integration/run_tests.sh freebox_system")


if __name__ == "__main__":
    main()
