#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Auto-generate tests/integration/integration_config.yml.vault.

Run once before integration tests:
    python3 tests/integration/setup_integration.py

- If integration_config.yml.vault already exists: exits immediately (noop).
- Reads app_id / app_token from Windows Credential Manager
  (works natively on Windows and from WSL via powershell.exe).
- Writes integration_config.yml, encrypts it with ansible-vault
  (prompts for vault password), then deletes the plaintext.
"""

from __future__ import print_function

import os
import subprocess
import sys
import tempfile

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_VAULT_FILE = os.path.join(_SCRIPT_DIR, "integration_config.yml.vault")
_CONFIG_FILE = os.path.join(_SCRIPT_DIR, "integration_config.yml")
_CRED_TARGET = "community-freebox-ansible"

_READ_CRED_PS = (
    r"""
$code = @'
using System; using System.Runtime.InteropServices; using System.Text;
public class WC {
    [StructLayout(LayoutKind.Sequential, CharSet=CharSet.Unicode)]
    public struct CRED {
        public int Flags,Type; public string TargetName,Comment;
        public System.Runtime.InteropServices.ComTypes.FILETIME LastWritten;
        public int BlobSize; public IntPtr Blob;
        public int Persist,AttrCount; public IntPtr Attrs;
        public string Alias,UserName;
    }
    [DllImport("advapi32",EntryPoint="CredReadW",CharSet=CharSet.Unicode,SetLastError=true)]
    public static extern bool Read(string t,int typ,int f,out IntPtr c);
    [DllImport("advapi32",SetLastError=true)] public static extern void Free(IntPtr c);
    public static string[] Get(string t){
        IntPtr p; if(!Read(t,1,0,out p)) return null;
        var c=(CRED)Marshal.PtrToStructure(p,typeof(CRED));
        byte[] b=new byte[c.BlobSize]; Marshal.Copy(c.Blob,b,0,b.Length); Free(p);
        return new string[]{c.UserName, Encoding.Unicode.GetString(b)};
    }
}
'@
Add-Type -TypeDefinition $code
$r = [WC]::Get("%(target)s")
if ($r) { "%(sep)s" + $r[0] + "%(sep)s" + $r[1] + "%(sep)s" }
"""
    % {"target": _CRED_TARGET, "sep": "|||"}
)


def _is_wsl():
    try:
        with open("/proc/version") as f:
            return "microsoft" in f.read().lower()
    except OSError:
        return False


def _read_wincred():
    wsl = _is_wsl()
    ps = "powershell.exe" if wsl else "powershell"
    with tempfile.NamedTemporaryFile(suffix=".ps1", mode="w",
                                     delete=False, encoding="utf-8") as tf:
        tf.write(_READ_CRED_PS)
        ps1 = tf.name
    # WSL: convert Linux path to Windows path for powershell.exe
    if wsl:
        win_ps1 = subprocess.check_output(
            ["wslpath", "-w", ps1], text=True
        ).strip()
    else:
        win_ps1 = ps1
    try:
        result = subprocess.run(
            [ps, "-NonInteractive", "-ExecutionPolicy", "Bypass", "-File", win_ps1],
            capture_output=True, text=True,
        )
    finally:
        os.unlink(ps1)

    if result.returncode != 0 or "|||" not in result.stdout:
        sys.stderr.write("ERROR: could not read '%s' from Windows Credential Manager.\n"
                         "       stderr: %s\n" % (_CRED_TARGET, result.stderr.strip()))
        sys.exit(1)

    parts = result.stdout.strip().split("|||")
    # parts = ['', app_id, app_token, '']
    return parts[1].strip(), parts[2].strip()


def _write_config(app_id, app_token):
    host_mac = os.environ.get("FREEBOX_TEST_HOST_MAC", "aa:bb:cc:dd:ee:ff")
    content = (
        "---\n"
        "# Generated by setup_integration.py — DO NOT COMMIT (gitignored)\n"
        "freebox_url: http://mafreebox.freebox.fr\n"
        "freebox_app_id: {app_id}\n"
        "freebox_app_token: {app_token}\n"
        "\n"
        "# MAC of a known LAN host for the freebox_lan_host target\n"
        "freebox_test_host_mac: \"{host_mac}\"\n"
    ).format(app_id=app_id, app_token=app_token, host_mac=host_mac)
    with open(_CONFIG_FILE, "w", encoding="utf-8") as f:
        f.write(content)
    os.chmod(_CONFIG_FILE, 0o600)


def _encrypt_and_cleanup():
    _vault_password_file = os.path.join(_SCRIPT_DIR, "get_vault_password.py")
    result = subprocess.run(
        ["ansible-vault", "encrypt",
         "--vault-password-file", _vault_password_file,
         _CONFIG_FILE]
    )
    if result.returncode != 0:
        sys.stderr.write("ERROR: ansible-vault encrypt failed.\n")
        # Leave plaintext so user can retry — but warn.
        sys.stderr.write("WARNING: %s left in plaintext. Delete it after fixing.\n"
                         % _CONFIG_FILE)
        sys.exit(1)
    os.rename(_CONFIG_FILE, _VAULT_FILE)
    print("OK: %s created." % _VAULT_FILE)


def main():
    if os.path.exists(_VAULT_FILE):
        print("OK: %s already exists — nothing to do." % _VAULT_FILE)
        sys.exit(0)

    print("Vault file not found — generating from Windows Credential Manager...")
    app_id, app_token = _read_wincred()
    _write_config(app_id, app_token)
    _encrypt_and_cleanup()


if __name__ == "__main__":
    main()
